### ISSUE TITLE
存在RANK问题，查询nvidia-smi显示显卡驱动正常

### ISSUE THREAD

**Issue by byronsit** [MengyangPu/EDTER#13]
(edge36) (venv) lu@lu:~/code/EDTER-main$ python tools/test.py
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.1'
Traceback (most recent call last):
  File "tools/test.py", line 139, in <module>
    main()
  File "tools/test.py", line 105, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/home/lu/code/EDTER-main/venv/lib/python3.6/site-packages/mmcv/runner/dist_utils.py", line 20, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/home/lu/code/EDTER-main/venv/lib/python3.6/site-packages/mmcv/runner/dist_utils.py", line 31, in _init_dist_pytorch
    rank = int(os.environ['RANK'])
  File "/usr/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'
(edge36) (venv) lu@lu:~/code/EDTER-main$

**Comment by MengyangPu** [comment]
[trian.py](https://github.com/MengyangPu/EDTER/blob/main/tools/train.py) 18 line: os.environ['RANK']='0'
