### ISSUE TITLE
KeyError: 'Rank' 

### ISSUE THREAD

**Issue by x33rak** [MengyangPu/EDTER#16]
What would be the solution for an error like this?

Traceback (most recent call last):
  File "tools/test.py", line 139, in <module>
    main()
  File "tools/test.py", line 105, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/data/name/anaconda3/envs/EDTER/lib/python3.8/site-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/data/name/anaconda3/envs/EDTER/lib/python3.8/site-packages/mmcv/runner/dist_utils.py", line 29, in _init_dist_pytorch
    rank = int(os.environ['RANK'])
  File "/data/name/anaconda3/envs/EDTER/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'

**Comment by x33rak** [comment]
Do I just need to uncomment that line?

**Comment by x33rak** [comment]
KeyError: 'BSDSDataset is not in the dataset registry'

Can you provide BSDSdataset as well?

**Comment by x33rak** [comment]
am i supposed to provide the img suffix and seg map suffix?

**Comment by x33rak** [comment]
> Please check [BSDSDataset class](https://github.com/MengyangPu/EDTER/blob/main/mmseg/datasets/bsds.py).

could you please elaborate on what I need to do in the BSDSDataset class?

**Comment by chenguilin111** [comment]
> What would be the solution for an error like this?
> 
> Traceback (most recent call last): File "tools/test.py", line 139, in main() File "tools/test.py", line 105, in main init_dist(args.launcher, **cfg.dist_params) File "/data/name/anaconda3/envs/EDTER/lib/python3.8/site-packages/mmcv/runner/dist_utils.py", line 18, in init_dist _init_dist_pytorch(backend, **kwargs) File "/data/name/anaconda3/envs/EDTER/lib/python3.8/site-packages/mmcv/runner/dist_utils.py", line 29, in _init_dist_pytorch rank = int(os.environ['RANK']) File "/data/name/anaconda3/envs/EDTER/lib/python3.8/os.py", line 675, in **getitem** raise KeyError(key) from None KeyError: 'RANK'

could you tell me how do you solve this problem?

**Comment by MengyangPu** [comment]
> > Please check [BSDSDataset class](https://github.com/MengyangPu/EDTER/blob/main/mmseg/datasets/bsds.py).
> 
> @MengyangPu could you please elaborate on what I need to do in the BSDSDataset class?

An incomplete environment may cause the above issue. Please check your environment, especially the following commands:

cd EDTER
pip install -e .  # or "python setup.py develop"
pip install -r requirements/optional.txt
