### ISSUE TITLE
gpu number

### ISSUE THREAD

**Issue by liuxingyu123** [MengyangPu/EDTER#17]
Hello, it is written in the paper that one v100gpu is used for training, while the document in the code says that eight GPUs are required. Can I ask whether the code can use one GPU for training.

**Comment by MengyangPu** [comment]
batch size = samples_per_gpu * gpu number.  For example, if you use one v100 gpu for training, please set "samples_per_gpu=8" and "gpu number=1".
Please modify "samples_per_gpu" in [configs files](https://github.com/MengyangPu/EDTER/tree/main/configs/bsds).

**Comment by liuxingyu123** [comment]
Hello, there are only samples in the config files configuration samples_per_gpu and workers_per_gpu.
I set GPUs to 1 by default in the train file parser, 
`group_gpus.add_argument(
        '--gpus',
        default=1,
        type=int,
        help='number of gpus to use '
        '(only applicable to non-distributed training)')`
and then the following error is reported
`Traceback (most recent call last):
  File "D:/graduate_study/code/EDTER-main/EDTER-main/tools/train.py", line 186, in <module>
    main()
  File "D:/graduate_study/code/EDTER-main/EDTER-main/tools/train.py", line 182, in main
    meta=meta)
  File "D:\graduate_study\code\EDTER-main\EDTER-main\mmseg\apis\train.py", line 108, in train_segmentor
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "D:\profession\Anaconda3\anaconda\envs\EDTER\lib\site-packages\mmcv\runner\iter_based_runner.py", line 130, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "D:\profession\Anaconda3\anaconda\envs\EDTER\lib\site-packages\mmcv\runner\iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "D:\profession\Anaconda3\anaconda\envs\EDTER\lib\site-packages\mmcv\parallel\data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "D:\graduate_study\code\EDTER-main\EDTER-main\mmseg\models\segmentors\base.py", line 154, in train_step
    losses = self(**data_batch)
  File "D:\profession\Anaconda3\anaconda\envs\EDTER\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\profession\Anaconda3\anaconda\envs\EDTER\lib\site-packages\mmcv\runner\fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "D:\graduate_study\code\EDTER-main\EDTER-main\mmseg\models\segmentors\base.py", line 124, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "D:\graduate_study\code\EDTER-main\EDTER-main\mmseg\models\segmentors\encoder_decoder.py", line 160, in forward_train
    x = self.extract_feat(img)
  File "D:\graduate_study\code\EDTER-main\EDTER-main\mmseg\models\segmentors\encoder_decoder.py", line 79, in extract_feat
    x = self.backbone(img)
  File "D:\profession\Anaconda3\anaconda\envs\EDTER\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\graduate_study\code\EDTER-main\EDTER-main\mmseg\models\backbones\vit_bimla.py", line 381, in forward
    x = self.patch_embed(x)  # [1, 1024, 32, 32]
  File "D:\profession\Anaconda3\anaconda\envs\EDTER\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\graduate_study\code\EDTER-main\EDTER-main\mmseg\models\backbones\vit_bimla.py", line 153, in forward
    x = self.proj(x)  # 1,1024,32,32
  File "D:\profession\Anaconda3\anaconda\envs\EDTER\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\profession\Anaconda3\anaconda\envs\EDTER\lib\site-packages\torch\nn\modules\conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "D:\profession\Anaconda3\anaconda\envs\EDTER\lib\site-packages\torch\nn\modules\conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

Process finished with exit code 1
`

**Comment by liuxingyu123** [comment]
its work ，thank you very much.

**Comment by liuxingyu123** [comment]
hello,When I modified the above configuration, I used an a6000 gpu and the gpu memory reached 30g. In the first stage of your paper, only 15g gpu memory is required. Do you know why?

**Comment by modric197** [comment]
> 
Hello, may I ask about the python environment that you install on your device with A6000 GPU? The environment offered by the author can only work on 2080Ti gpu but failed on A6000 gpu. Thank you!

**Comment by hhqweasd** [comment]
> hello,When I modified the above configuration, I used an a6000 gpu and the gpu memory reached 30g. In the first stage of your paper, only 15g gpu memory is required. Do you know why?

The used memory depends on **_samples_per_gpu_**. The used memory reaches in per V100 GPU reaches 15G and 25G when we set sample per gpu to 1 and 4, respectively. So it may reach a larger used memory when samples_per_gpu is larger.
