### ISSUE TITLE
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.1'

### ISSUE THREAD

**Issue by byronsit** [MengyangPu/EDTER#19]
(edge36) (venv) lu@lu:~/code/EDTER-main$ python tools/test.py
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.1'
Traceback (most recent call last):
  File "tools/test.py", line 142, in <module>
    main()
  File "tools/test.py", line 108, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/home/lu/code/EDTER-main/venv/lib/python3.6/site-packages/mmcv/runner/dist_utils.py", line 20, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/home/lu/code/EDTER-main/venv/lib/python3.6/site-packages/mmcv/runner/dist_utils.py", line 33, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero

我检测过了，显卡驱动什么的都是正常的，但是运行这个python tools/test.py就会显示找不到CUDA,用了两台电脑都出现这样的错误，是不是python setup.py 这个有问题？

**Comment by byronsit** [comment]
python
Python 3.6.9 (default, Mar 15 2022, 13:55:28) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> exit()
(edge36) (venv) lu@lu:~/code/EDTER-main$

**Comment by byronsit** [comment]
请问如何对自己的图片进行边缘检测，不是检测BSDS500数据集的图片

**Comment by leesureel** [comment]
我也遇到了同样的问题，训练的时候没问题，测试就有问题了，找不到GPU

**Comment by chenguilin111** [comment]
> 

请问你后面是如何解决的呢？

**Comment by chenguilin111** [comment]
> (edge36) (venv) lu@lu:~/code/EDTER-main$ python tools/test.py No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.1' Traceback (most recent call last): File "tools/test.py", line 142, in main() File "tools/test.py", line 108, in main init_dist(args.launcher, **cfg.dist_params) File "/home/lu/code/EDTER-main/venv/lib/python3.6/site-packages/mmcv/runner/dist_utils.py", line 20, in init_dist _init_dist_pytorch(backend, **kwargs) File "/home/lu/code/EDTER-main/venv/lib/python3.6/site-packages/mmcv/runner/dist_utils.py", line 33, in _init_dist_pytorch torch.cuda.set_device(rank % num_gpus) ZeroDivisionError: integer division or modulo by zero
> 
> 我检测过了，显卡驱动什么的都是正常的，但是运行这个python tools/test.py就会显示找不到CUDA,用了两台电脑都出现这样的错误，是不是python setup.py 这个有问题？

请问你是如何解决的呢

**Comment by MengyangPu** [comment]
> 我也遇到了同样的问题，训练的时候没问题，测试就有问题了，找不到GPU

找到../tools/test.py这个文件，注释掉line14-17行的代码再运行测试试一下。另外，line3强制指定了GPU，请酌情修改或注释。
../tools/test_local.py同上。
