### ISSUE TITLE
Testing with images of different resolutions will report an error

### ISSUE THREAD

**Issue by Li-yachuan** [MengyangPu/EDTER#24]
I have successfully tested the results of the pretrained model on bsds-test, which is consistent with the paper. What an incredible job!
But when I want to test images of other resolutions, an error will be reported, as follows:
Since I have not used the mmseg framework before, it is difficult for me to solve this problem in a short time. Could you please provide me with some help?
Here is the command I run：
`CUDA_VISIBLE_DEVICES=1 python tools/test_local.py --gpu-collect --aug-test --launcher none --eval "" --show-dir "./output-bsds-train"`
This is the prompt error：
Traceback (most recent call last):
  File "tools/test_local.py", line 162, in <module>
    main()
  File "tools/test_local.py", line 150, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
  File "/workspace/EDTER-main/mmseg/apis/test.py", line 48, in single_gpu_test
    result = model(return_loss=False, **data)[0][0]
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/workspace/EDTER-main/mmseg/models/segmentors/base.py", line 126, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/workspace/EDTER-main/mmseg/models/segmentors/base.py", line 108, in forward_test
    return self.aug_test(imgs, img_metas, **kwargs)
  File "/workspace/EDTER-main/mmseg/models/segmentors/encoder_decoder_local8x8.py", line 592, in aug_test
    img0_crop_seg_logit = self.slide_inference2(img0_crop, img_metas[0], rescale)
  File "/workspace/EDTER-main/mmseg/models/segmentors/encoder_decoder_local8x8.py", line 502, in slide_inference2
    fuse_outs = self._fuse_head_forward_test(local_features, global_features)
  File "/workspace/EDTER-main/mmseg/models/segmentors/encoder_decoder_local8x8.py", line 132, in _fuse_head_forward_test
    fuse_logits, _ = self.fuse_head.fuse_forward_test(local_features, global_features)
  File "/workspace/EDTER-main/mmseg/models/decode_heads/decode_head.py", line 289, in fuse_forward_test
    fuse_logits, fuse_features = self.forward(inputs1,inputs2)
  File "/workspace/EDTER-main/mmseg/models/decode_heads/local8x8_fuse_head.py", line 72, in forward
    fuse_features = self.SFT_head(local_features, global_features)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/EDTER-main/mmseg/models/decode_heads/local8x8_fuse_head.py", line 34, in forward
    fuse_features = local_features * (scale+1) +shift
RuntimeError: The size of tensor a (448) must match the size of tensor b (454) at non-singleton dimension 2

**Comment by x33rak** [comment]
@Yachuan-Li I was wondering how you solved the "KeyError: 'BSDSDataset is not in the dataset registry'" error?

**Comment by Bedrettin-Cetinkaya** [comment]
@Yachuan-Li Hello, I suffer from the same problem. Can you solve it?

**Comment by Yachuan-Li** [comment]
Interpolating to the same size does not seem to make much difference to the results




---Original---
From: "Bedrettin ***@***.***&gt;
Date: Fri, Aug 5, 2022 19:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MengyangPu/EDTER] Testing with images of different resolutionswill report an error (Issue #24)




 
@Yachuan-Li Hello, I suffer from the same problem. Can you solve it?

**Comment by FengYuQ** [comment]
> Interpolating to the same size does not seem to make much difference to the results

what’s mean that Interpolating to the same size？I want to use my image data in this model which is different resolutions with the test image.So Could you tell me how to solve this problem?

**Comment by FengYuQ** [comment]
> Interpolating to the same size does not seem to make much difference to the results

what’s mean that Interpolating to the same size？I want to use my image data in this model which is different resolutions with the test image.So Could you tell me how to solve this problem?

**Comment by Yachuan-Li** [comment]
I was just testing and didn't encounter this problem.
I guess, did you install MMSEG separately without referencing the one that came with the project?


---Original---
From: "Xeerak ***@***.***&gt;
Date: Tue, Aug 2, 2022 04:17 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MengyangPu/EDTER] Testing with images of different resolutionswill report an error (Issue #24)




 
@Yachuan-Li I was wondering how you solved the "KeyError: 'BSDSDataset is not in the dataset registry'" error?

**Comment by hhqweasd** [comment]
When using a different image resolution, the transformation (e.g., resize, crop.) on the input image is required to avoid such a problem.
