### ISSUE TITLE
The model and loaded state dict do not match exactly

### ISSUE THREAD

**Issue by yuuy07** [MengyangPu/EDTER#51]
when I run tools\test.py, the model and loaded state dict do not match exactly. I have downloaded "jx_vit_large_p16_384-b3be5167.pth", but the error still exist

**Comment by yuuy07** [comment]
The error is 
"Traceback (most recent call last):
  File "test.py", line 140, in <module>
    main()
  File "test.py", line 123, in main
    model.PALETTE = checkpoint['meta']['PALETTE']
KeyError: 'PALETTE'"

**Comment by kulkarnikeerti** [comment]
I think `jx_vit_large_p16_384-b3be5167.pth` is not the checkpoint you use it for the model testing. You need to download the pretrained model from the `[here](https://drive.google.com/drive/folders/1OkdakKKIMRGnKH8mxuFi_qI9sa903CD2)`

**Comment by yuuy07** [comment]
> I think `jx_vit_large_p16_384-b3be5167.pth` is not the checkpoint you use it for the model testing. You need to download the pretrained model from the `[here](https://drive.google.com/drive/folders/1OkdakKKIMRGnKH8mxuFi_qI9sa903CD2)`

Thanks for your suggestion!! I've tried this way, but I meet a new error :"size mismatch for backbone.mla.mla_b3.0.weight: copying a param with shape torch.Size([256, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3])."

**Comment by kulkarnikeerti** [comment]
I am not sure of this error. Even I am trying to test the model but I have different error message. 
```
  File "./tools/test.py", line 142, in <module>
    main()
  File "./tools/test.py", line 129, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
  File "/home/keerti/PycharmProjects/EDTER-main/mmseg/apis/test.py", line 65, in single_gpu_test
    out_file=out_file)
  File "/home/keerti/PycharmProjects/EDTER-main/mmseg/models/segmentors/base.py", line 253, in show_result
    color_seg[seg == label, :] = color
IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed
```

Did you encounter this kind of error by any chance?

**Comment by yuuy07** [comment]
Sorry，I didn‘t encounter this error
