### ISSUE TITLE
Error when calculating MIOU

### ISSUE THREAD

**Issue by wangxiang-wx** [MengyangPu/EDTER#73]
[>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1000/1000, 7.1 task/s, elapsed: 141s, ETA:     0sTraceback (most recent call last):
  File "E:\EDTER_Edge_detection\EDTER-main\train.py", line 175, in <module>
    main()
  File "E:\EDTER_Edge_detection\EDTER-main\train.py", line 164, in main
    train_segmentor(
  File "E:\EDTER_Edge_detection\EDTER-main\mmseg\apis\train.py", line 111, in train_segmentor
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "D:\Anaconda\envs\EDTER\lib\site-packages\mmcv\runner\iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "D:\Anaconda\envs\EDTER\lib\site-packages\mmcv\runner\iter_based_runner.py", line 70, in train
    self.call_hook('after_train_iter')
  File "D:\Anaconda\envs\EDTER\lib\site-packages\mmcv\runner\base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "E:\EDTER_Edge_detection\EDTER-main\mmseg\core\evaluation\eval_hooks.py", line 30, in after_train_iter
    self.evaluate(runner, results)
  File "E:\EDTER_Edge_detection\EDTER-main\mmseg\core\evaluation\eval_hooks.py", line 34, in evaluate
    eval_res = self.dataloader.dataset.evaluate(
  File "E:\EDTER_Edge_detection\EDTER-main\mmseg\datasets\custom.py", line 342, in evaluate
    all_acc, acc, iou = mean_iou(
  File "E:\EDTER_Edge_detection\EDTER-main\mmseg\core\evaluation\mean_iou.py", line 62, in mean_iou
    intersect_and_union(results[i], gt_seg_maps[i], num_classes,
  File "E:\EDTER_Edge_detection\EDTER-main\mmseg\core\evaluation\mean_iou.py", line 23, in intersect_and_union
    pred_label = pred_label[mask]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 425

Process finished with exit code 1

**Comment by wangxiang-wx** [comment]
for i in range(num_imgs):
        ##############################################################################
        ##############################################################################
        ##pred_label的输入值
        results_i = results[i]
        ##查看其shape
        results_i_shape = results_i.shape
        # print("results_i", results_i)
        ##发现其为a*b*c*d四维向量,（1,1,b,c）
        print("results[i]的维度=======", results_i_shape)
        ##前两个维度是多余的，因此需要将其变为二维，以便计算miou
        ## 采用保留后两个维度的方式,表示获取矩阵 results_i 的所有后两个维度的行和列，然后选取深度方向上索引为 0 的元素
        results_i = results_i[0, 0, :, :]
        # 判断是否降维成功
        shape_after = results_i.shape
        print("降低维度后results[i]的维度=======", shape_after)
I solved this problem by modifying the dimension of the result [i] matrix from four dimensions to two dimensions. Currently, the code can run, but I'm not sure if the results are correct

**Comment by MengyangPu** [comment]
Our project is developed based on [MMsegmentation](https://github.com/open-mmlab/mmsegmentation), which is used for image segmentation. And the mIoU is used for segmentation evaluation. We do not use 'mean_iou.py' to evaluate the edge results. If you want to evaluate edges, please refer to [here](https://github.com/MengyangPu/EDTER/tree/main/eval).
