### ISSUE TITLE
issues when using my own dataset

### ISSUE THREAD

**Issue by wangxiang-wx** [MengyangPu/EDTER#75]
hello，when I using my own dataset，I found a loss of 0.000, and during validation, indicators such as Iou and mIoU were also 0, which seems incorrect. However, these indicators seem to be indicators of semantic segmentation. Don't you need to consider these, just focus on the final evaluation results? When I used the bsds500 dataset, the loss was not 0.00 and kept decreasing, but the IoU and MIoU indicators were always 0. Can you explain why these indicators need to be considered

```python
2023-09-14 11:50:02,234 - mmseg - INFO - Iter(val) [2500]	mIoU: 0.0000, mAcc: 0.0000, aAcc: 0.0000
2023-09-14 11:50:06,251 - mmseg - INFO - Iter [2520/10000]	lr: 7.724e-07, eta: 1:12:23, time: 9.334, data_time: 9.133, memory: 7677, decode.loss_seg: 0.0000, aux_0.loss_seg: 0.0000, aux_1.loss_seg: 0.0000, aux_2.loss_seg: 0.0000, aux_3.loss_seg: 0.0000, aux_4.loss_seg: 0.0000, aux_5.loss_seg: 0.0000, aux_6.loss_seg: 0.0000, aux_7.loss_seg: 0.0000, loss: 0.0000
```

**Comment by wangxiang-wx** [comment]
Because I used the wrong pre-training file (located in pretrain/jx_vit_...) when training my own data set？ or because some parameters were not adjusted when I trained my own data set.

**Comment by MengyangPu** [comment]
In our project, we do not use validation. If you use validation, then you will call the validation codes in MMsegmentation.

**Comment by wangxiang-wx** [comment]
```python
2023-09-14 23:14:32,497 - mmseg - INFO - Iter [80/5000]	lr: 9.859e-07, eta: 0:26:17, time: 0.259, data_time: 0.003, memory: 8029, decode.loss_seg: 0.0000, aux_0.loss_seg: 0.0000, aux_1.loss_seg: 0.0000, aux_2.loss_seg: 0.0000, aux_3.loss_seg: 0.0000, aux_4.loss_seg: 0.0000, aux_5.loss_seg: 0.0000, aux_6.loss_seg: 0.0000, aux_7.loss_seg: 0.0000, fuse_edge.loss_seg: 0.0000, loss: 0.0000
[                                                  ] 0/1, elapsed: 0s, ETA:Traceback (most recent call last):
  File "E:\EDTER_Edge_detection\EDTER-main\train_local.py", line 176, in <module>
    main()
  File "E:\EDTER_Edge_detection\EDTER-main\train_local.py", line 165, in main
    train_segmentor(
  File "E:\EDTER_Edge_detection\EDTER-main\mmseg\apis\train.py", line 112, in train_segmentor
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "D:\Anaconda\envs\EDTER\lib\site-packages\mmcv\runner\iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "D:\Anaconda\envs\EDTER\lib\site-packages\mmcv\runner\iter_based_runner.py", line 70, in train
    self.call_hook('after_train_iter')
  File "D:\Anaconda\envs\EDTER\lib\site-packages\mmcv\runner\base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "E:\EDTER_Edge_detection\EDTER-main\mmseg\core\evaluation\eval_hooks.py", line 29, in after_train_iter
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "E:\EDTER_Edge_detection\EDTER-main\mmseg\apis\test.py", line 36, in single_gpu_test
    result = model(return_loss=False, **data)
  File "D:\Anaconda\envs\EDTER\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Anaconda\envs\EDTER\lib\site-packages\mmcv\parallel\data_parallel.py", line 51, in forward
    return super().forward(*inputs, **kwargs)
  File "D:\Anaconda\envs\EDTER\lib\site-packages\torch\nn\parallel\data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "D:\Anaconda\envs\EDTER\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Anaconda\envs\EDTER\lib\site-packages\mmcv\runner\fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "E:\EDTER_Edge_detection\EDTER-main\mmseg\models\segmentors\base.py", line 126, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "E:\EDTER_Edge_detection\EDTER-main\mmseg\models\segmentors\base.py", line 106, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "E:\EDTER_Edge_detection\EDTER-main\mmseg\models\segmentors\encoder_decoder_local8x8.py", line 498, in simple_test
    seg_pred = self.inference(img, img_meta, rescale)
  File "E:\EDTER_Edge_detection\EDTER-main\mmseg\models\segmentors\encoder_decoder_local8x8.py", line 480, in inference
    seg_logit = self.slide_inference(img, img_meta, rescale)
  File "E:\EDTER_Edge_detection\EDTER-main\mmseg\models\segmentors\encoder_decoder_local8x8.py", line 375, in slide_inference
    fuse_outs_crop = self._fuse_head_forward_test(local_features_crop, global_features_crop)
  File "E:\EDTER_Edge_detection\EDTER-main\mmseg\models\segmentors\encoder_decoder_local8x8.py", line 132, in _fuse_head_forward_test
    fuse_logits, _ = self.fuse_head.fuse_forward_test(local_features, global_features)
  File "E:\EDTER_Edge_detection\EDTER-main\mmseg\models\decode_heads\decode_head.py", line 289, in fuse_forward_test
    fuse_logits, fuse_features = self.forward(inputs1,inputs2)
  File "E:\EDTER_Edge_detection\EDTER-main\mmseg\models\decode_heads\local8x8_fuse_head.py", line 70, in forward
    fuse_features = self.SFT_head(local_features, global_features)
  File "D:\Anaconda\envs\EDTER\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\EDTER_Edge_detection\EDTER-main\mmseg\models\decode_heads\local8x8_fuse_head.py", line 36, in forward
    fuse_features = local_features * (scale+1) +shift
RuntimeError: The size of tensor a (1272) must match the size of tensor b (1279) at non-singleton dimension 3

Process finished with exit code 1

```

**Comment by wangxiang-wx** [comment]
当我用自己数据集训练train_local的时候，在又报了这样的错误
```python
RuntimeError: The size of tensor a (552) must match the size of tensor b (559) at non-singleton dimension 3
``` 
似乎在第一阶段训练时候是正常的，但第二阶段训练中每500轮执行evaluation时候便会报错，似乎不能在1、2阶段进行融合。但奇怪的是，这一现象在我复现BSDS数据集时候并没有发生，仅在复现我自己数据集时候发生。我已经反复检查，输入是绝对没有问题的，GT与img的分辨率是相同的。请问可能是哪里出了问题呢

**Comment by wangxiang-wx** [comment]
可能bads数据集图片分辨率都是481✖321或321✖481，才能顺利滑动窗口。因此，在制作我们自己数据集时，也要保持相同的规律。我会对图片进行resize后再进行测试，应该是可行的！
