### ISSUE TITLE
issues when run train command

### ISSUE THREAD

**Issue by allyli** [MengyangPu/EDTER#84]
Traceback (most recent call last):
  File "./tools/train.py", line 168, in <module>
    main()
  File "./tools/train.py", line 109, in main
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
  File "/home/jovyan/extra_lib/edter/lib/python3.7/site-packages/mmcv/utils/config.py", line 432, in dump
    f.write(self.pretty_text)
  File "/home/jovyan/extra_lib/edter/lib/python3.7/site-packages/mmcv/utils/config.py", line 387, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
TypeError: FormatCode() got an unexpected keyword argument 'verify'
Traceback (most recent call last):
  File "./tools/train.py", line 168, in <module>
    main()
  File "./tools/train.py", line 109, in main
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
  File "/home/jovyan/extra_lib/edter/lib/python3.7/site-packages/mmcv/utils/config.py", line 432, in dump
    f.write(self.pretty_text)
  File "/home/jovyan/extra_lib/edter/lib/python3.7/site-packages/mmcv/utils/config.py", line 387, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
TypeError: FormatCode() got an unexpected keyword argument 'verify'
Traceback (most recent call last):
  File "/home/jovyan/extra_lib/edter/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jovyan/extra_lib/edter/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jovyan/extra_lib/edter/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/jovyan/extra_lib/edter/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/jovyan/extra_lib/edter/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/bsds/EDTER_BIMLA_320x320_80k_bsds_bs_8.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by MengyangPu** [comment]
@allyli 
Hi, it may be an issue with mmcv. Please refer to [this answer](https://github.com/open-mmlab/mmdetection/issues/10962).

**Comment by allyli** [comment]
This is a good way, thanks so much!







At 2023-11-27 19:42:02, "Mengyang Pu" ***@***.***> wrote:

Hi, it may be an issue with mmcv. Please refer to this answer.
